### ISSUE TITLE
这种污染搜索结果的可不可以也屏蔽下

### ISSUE THREAD

**Issue by psychosispy** [BonjourFeng/Github-Search-Purification#1]
[code-help-tutor](https://github.com/code-help-tutor)
[turbocanary](https://github.com/turbocanary)

**Comment by BonjourFeng** [comment]
已更新，感谢。

**Comment by pooneyy** [comment]
> 已更新，感谢。


以后我要是再遇到类似的，还能在这里继续提交吗？

**Comment by BonjourFeng** [comment]
> > 已更新，感谢。
> 
> 以后我要是再遇到类似的，还能在这里继续提交吗？

可以的，不过到[Greasyfork的反馈区](https://greasyfork.org/zh-CN/scripts/473912-github%E6%90%9C%E7%B4%A2%E5%87%80%E5%8C%96)反馈可能更好一点
