### ISSUE TITLE
请求屏蔽一些仓库

### ISSUE THREAD

**Issue by pooneyy** [BonjourFeng/Github-Search-Purification#2]
[scifox-kouko/ADE-](https://github.com/scifox-kouko/ADE-)

**Comment by BonjourFeng** [comment]
请问这个仓库有什么问题吗？

这个似乎是个空仓库，单纯的空仓库不在脚本计划屏蔽的对象里，除非它对搜索结果产生了很大的负面影响

**Comment by pooneyy** [comment]
> 请问这个仓库有什么问题吗？
> 
> 这个似乎是个空仓库，单纯的空仓库不在脚本计划屏蔽的对象里，除非它对搜索结果产生了很大的负面影响

这是一个能被搜到的空仓库
https://github.com/search?q=%E6%84%8F%E9%97%B4AI&type=repositories&p=2
![image](https://github.com/BonjourFeng/Github-Search-Purification/assets/85266337/a1f44a2e-68b8-4850-86f2-cf1e50f08775)

**Comment by BonjourFeng** [comment]
这个用户应该不会添加到脚本的屏蔽名单里

脚本目前的屏蔽方式是直接屏蔽名单中用户的所有库，如果只因为这个普通的空仓库就屏蔽这个用户，可能有点不妥

**你可以在脚本的ban列表中手动添加这个用户的名称（scifox-koudo）**

近期我会更新一下README，明确一下创建哪种仓库的用户会添加到自带的屏蔽列表里，长期也可能会更新在设置界面里屏蔽用户的功能

感谢你的建议

**Comment by BonjourFeng** [comment]
这个用户应该不会添加到脚本的屏蔽名单里

脚本目前的屏蔽方式是直接屏蔽名单中用户的所有库，如果只因为这个普通的空仓库就屏蔽这个用户，可能有点不妥

**你可以在脚本的ban列表中手动添加这个用户的名称（scifox-koudo）**

近期我会更新一下README，明确一下创建哪种仓库的用户会添加到自带的屏蔽列表里，长期也可能会更新在设置界面里屏蔽用户的功能

感谢你的建议
