### ISSUE TITLE
就很棒！

### ISSUE THREAD

**Issue by Aeant** [BonjourFeng/Github-Search-Purification#7]
非常棒，自己用AI也搞了一个，不过名单列表没有你的那么多，建议名字库名字也搞成中文的，便于大伙搜索到；那些虚假不良信息太恶心了，强烈抵制

**Comment by BonjourFeng** [comment]
感谢支持，建议在[GreasyFork](https://greasyfork.org/zh-CN/scripts/473912-github%E6%90%9C%E7%B4%A2%E5%87%80%E5%8C%96)上订阅脚本

**Comment by Mikachu2333** [comment]
感激不尽！太有效了！！！
